config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :home
  resources :contents do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  validates :title, presence: true
  validates :datetime, presence: true

  belongs_to :user
  belongs_to :content
  
  # include RankedModel 
  # ranks :row_order, with_same: :content_id
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :password, presence: true, length: { minimum: 6, maximum: 200 }, on: :create
  validates :email, presence: true

  has_many :cards
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_content, :set_user

  def new
    @card = Card.new
    
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to root_path
    else
      render action: :new
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  def edit
    @card = Card.find(params[:id])
    @contents = Content.all
  end

  def update
    @card = Card.find(params[:id])
    @card.update(edit_params)
    redirect_to root_path
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to root_path
  end

  private
  def card_params
    params.require(:card).permit(:title, :comment, :datetime, :content_id).merge(content_id: params[:content_id]).merge(user_id: current_user.id)
  end

  def edit_params
    params.require(:card).permit(:title, :comment, :datetime, :content_id).merge(user_id: current_user.id)
  end

  def set_content
    @content = Content.find(params[:content_id])
  end

  def set_user
    @user = User.find_by(id: current_user.id)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contents = Content.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.erb
<div class="new-container">
  <%= render '/home/header' %>

  <div class="card-content">
    <div class="card-box">
      <%= form_with model: [@content,@card], local: true do |f| %>
        <h2 class="card-add">
          カードを編集
        </h2>
        <%= f.text_field :title, type: "text", class: "card-title", placeholder: "タイトルを入力してください" %>
        <p class="date-text">終了予定</p>
        <%= f.datetime_select :datetime, {use_two_digit_numbers:true, discard_year: true}, class: "card-date" %>
        <p class='content-data'>カードを移動</p>
        <%= f.select :content_id, @contents.map {|content| [content.text, content.id]}, {}, {class: 'card-move'} %>
        <%= f.text_area :comment, type: "text", class: "card-comment", placeholder: "コメントを入力してください" %>
        <%= f.submit "編集する", class: "card-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<div class="new-container">
  <%= render '/home/header' %>

  <div class="card-content">
    <div class="card-box">
      <%= form_with model: [@content,@card], local: true do |f| %>
        <h2 class="card-add">
          カードを追加
        </h2>
        <%= f.text_field :title, type: "text", class: "card-title", placeholder: "タイトルを入力してください" %>
        <p class="date-text">終了予定</p>
        <%= f.datetime_select :datetime, {use_two_digit_numbers:true, discard_year: true}, class: "card-date" %>
        <%= f.text_area :comment, type: "text", class: "card-comment", placeholder: "コメントを入力してください" %>
        <%= f.submit "追加する", class: "card-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<div class="new-container">
  <%= render '/home/header' %>

  <div class="card-content">
    <div class="card-box">
      <h2 class="card-add">
        カード詳細
      </h2>
      <div class="card-show__title-box">
        <p class="card-show__title-box__text">タイトル</p>
        <h2 class="card-show__title-box__title">
          <%= @card.title %>
        </h2>
      </div>
      <div class="card-show__datetime-box">
        <p class="card-show__datetime-box__text">終了予定</p>
        <h2 class="card-show__datetime-box__datetime">
          <%= @card.datetime.strftime("%-m月%-d日 %-H時%-M分") %>
        </h2>
      </div>
      <div class="card-show__comment__box">
        <p class="card-show__comment__box__text">コメント</p>
        <h2 class="card-show__comment__box__comment">
          <%= @card.comment %>
        </h2>
      </div>
      <div class="button-box">
        <div class="card-edit">
          <%= link_to edit_content_card_path do %>
            <div class="card-edit__box">
              <h2 class="card-edit__box-button">
                カードを編集
              </h2>
            </div>
          <%end%>
        </div>
        <div class="card-delete">
          <%= link_to content_card_path, method: :delete do %>
            <div class="card-delete__box">
              <h2 class="card-delete__box-button">
                カードを削除
              </h2>
            </div>
          <%end%>
        </div>
      </div>
      <div class="card-home">
        <%= link_to root_path do %>
          <div class="card-home__box">
            <h2 class="card-home__box-button">
              ホームに戻る
            </h2>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/home/_content.html.erb
<%# <%= content_tag "tr", id: "card-#{card.id}", class: "item", data: { model_name: card.class.name.underscore, update_url: card_sort_path(card)} do %>
<div class="task-content">
  <div class="task-content__list">
    <h2 class="task-content__list-title">
    <%= content.text %>
    </h2>
    <%= link_to new_content_card_path(content) do %>
      <h2 class="task-content__list-add">
        カードを作成
      </h2>
    <% end %>
    <div class="task-content__list-box">
      <% content.cards.each do |card| %>
      <% if card.user_id == current_user.id %>
        <div class="task-content__list-box__div">
          <%= link_to content_card_path(content,card) do %>
            <div class="task-content__list-box__div-card">
              <h2 class="task-content__list-box__div-card__title">
                <%= card.title %>
              </h2>
              <h2 class="task-content__list-box__div-card__datetime">
                <%= card.datetime.strftime("%-m月%-d日 %-H時%-M分") %>
              </h2>
            </div>
          <% end %>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<%# <% end %>

app/views/home/_header.html.erb
<div class="header">
  <div class="title">
    <%= link_to "One-day", root_path %>
  </div>
  <% if user_signed_in? %>
    <div class="logout">
      <%= link_to destroy_user_session_path, method: "delete" do %>
        <div class="log-out">
          <h2 class="log-out__text">ログアウト</h2>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="devise">
      <div class="login">
        <%= link_to new_user_session_path do %>
          <div class="log-in">
            <h2 class="log-in__text">ログイン</h2>
          </div>
        <% end %>
      </div>
      <%= link_to new_user_registration_path do %>
        <div class="new-user">
          <h2 class="new-user__text">新規登録</h2>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="home-container">
  <%= render 'header' %>

  <div class="content">
    <%= render partial: "content", collection: @contents %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneDay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript"
      src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>